---
abstract: 'upload files to a Google Code project'
author:
  - 'Fayland Lam <fayland@gmail.com>'
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300017, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-DOHERTY
no_index:
  directory:
    - corpus
requires:
  Carp: 0
  Exporter: 0
  File::Basename: 0
  HTTP::Request::Common: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Scalar::Util: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-PluginBundle-Author-DOHERTY/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-Author-DOHERTY/
  repository: git://github.com/doherty/Dist-Zilla-PluginBundle-Author-DOHERTY.git
version: 0.006
