---
abstract: 'configure Dist::Zilla like DOHERTY'
author:
  - 'Mike Doherty <doherty@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300006, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-DOHERTY
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla: 4.102341
  Dist::Zilla::Plugin::CheckChangesHasContent: 0
  Dist::Zilla::Plugin::CheckExtraTests: 0
  Dist::Zilla::Plugin::Clean: 0
  Dist::Zilla::Plugin::CopyFilesFromBuild: 0
  Dist::Zilla::Plugin::Git::Check: 0
  Dist::Zilla::Plugin::Git::Commit: 0
  Dist::Zilla::Plugin::Git::NextVersion: 0
  Dist::Zilla::Plugin::Git::Tag: 1.112380
  Dist::Zilla::Plugin::GitHub: 0.13
  Dist::Zilla::Plugin::InstallGuide: 0
  Dist::Zilla::Plugin::InstallRelease: 0.006
  Dist::Zilla::Plugin::MinimumPerl: 1.003
  Dist::Zilla::Plugin::OurPkgVersion: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::ReadmeFromPod: 0
  Dist::Zilla::Plugin::SurgicalPodWeaver: 0.0015
  Dist::Zilla::Plugin::Twitter: 0.010
  Dist::Zilla::PluginBundle::TestingMania: 0
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0.99
  Moose::Autobox: 0
  Pod::Weaver::PluginBundle::Author::DOHERTY: 0.006
  Pod::Weaver::Section::BugsAndLimitations: 1.102670
  WWW::Shorten::Googl: 0
  autodie: 2.00
  namespace::autoclean: 0.09
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doherty/Dist-Zilla-PluginBundle-Author-DOHERTY/issues
  homepage: http://metacpan.org/release/Dist-Zilla-PluginBundle-Author-DOHERTY/
  repository: git://github.com/doherty/Dist-Zilla-PluginBundle-Author-DOHERTY.git
version: 0.25
